# -*- coding: utf-8 -*-
"""Life-Expectancy analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10kx02qMM9U1yDzwEGzGILClE8cC5U2WX

# Dataset Information

This project uses a public Life Expectancy dataset commonly available on Kaggle and based on health, economic, and demographic indicators from WHO and related sources.

###Expected File Name

###After downloading the dataset, place the CSV file in this folder using the name:

##life_expectancy_data.csv`

## Dataset Source

###Dataset source: Add Kaggle dataset https://www.kaggle.com/datasets/kumarajarshi/life-expectancy-who.

## Note

###The dataset may not be included directly in this repository due to licensing or file size considerations. Users can download the dataset from the original source and place it in this folder before running the notebook.

# Life Expectancy Analysis

## 1. Introduction
## 2. Import Libraries
## 3. Load Dataset
## 4. Data Overview
## 5. Data Cleaning
## 6. Exploratory Data Analysis
## 7. Correlation Analysis
## 8. Feature Engineering
## 9. Machine Learning Model
## 10. Model Evaluation
## 11. Key Insights
## 12. Conclusion
"""

# Life Expectancy Analysis

# 1. Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Display settings
pd.set_option("display.max_columns", None)
sns.set(style="whitegrid")

# 2. Load dataset

data_path = "/content/Life Expectancy Data.xls"

df = pd.read_csv(data_path)

df.head()
#df.tail()

# 3. Data overview

print("Dataset shape:", df.shape)

df.info()

# Summary statistics

df.describe()

# Check missing values

missing_values = df.isnull().sum().sort_values(ascending=False)
missing_values

"""##Clean column names"""

# 4. Clean column names

df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
    .str.replace("-", "_")
    .str.replace("/", "_")
)

df.columns

"""##Handle missing values"""

# 5. Handle missing values

# Fill numerical missing values with median
numeric_cols = df.select_dtypes(include=["int64", "float64"]).columns

for col in numeric_cols:
    df[col] = df[col].fillna(df[col].median())

# Fill categorical missing values with mode
categorical_cols = df.select_dtypes(include=["object"]).columns

for col in categorical_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

df.isnull().sum().sum()

"""##Exploratory data analysis"""

# 6. Life expectancy distribution

plt.figure(figsize=(10, 6))
sns.histplot(df["life_expectancy"], kde=True)
plt.title("Distribution of Life Expectancy")
plt.xlabel("Life Expectancy")
plt.ylabel("Frequency")
plt.show()

"""##Life expectancy over time"""

# 7. Average life expectancy by year

life_by_year = df.groupby("year")["life_expectancy"].mean().reset_index()

plt.figure(figsize=(10, 6))
sns.lineplot(data=life_by_year, x="year", y="life_expectancy", marker="o")
plt.title("Average Life Expectancy Over Time")
plt.xlabel("Year")
plt.ylabel("Average Life Expectancy")
plt.show()

"""##Developed vs developing countries"""

# 8. Life expectancy by development status

if "status" in df.columns:
    plt.figure(figsize=(8, 5))
    sns.boxplot(data=df, x="status", y="life_expectancy")
    plt.title("Life Expectancy by Country Development Status")
    plt.xlabel("Status")
    plt.ylabel("Life Expectancy")
    plt.show()

"""##Correlation analysis"""

# 9. Correlation heatmap

plt.figure(figsize=(14, 10))
correlation = df.select_dtypes(include=["int64", "float64"]).corr()

sns.heatmap(correlation, cmap="coolwarm", annot=False)
plt.title("Correlation Heatmap")
plt.show()

# Correlation with life expectancy

correlation["life_expectancy"].sort_values(ascending=False)

"""##Prepare data for modeling"""

# 10. Prepare data for machine learning

# Encode categorical columns
df_model = df.copy()

for col in df_model.select_dtypes(include=["object"]).columns:
    encoder = LabelEncoder()
    df_model[col] = encoder.fit_transform(df_model[col])

# Define target
target = "life_expectancy"

X = df_model.drop(columns=[target])
y = df_model[target]

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

X_train.shape, X_test.shape

"""##Linear Regression model"""

# 11. Linear Regression model

linear_model = LinearRegression()
linear_model.fit(X_train, y_train)

linear_predictions = linear_model.predict(X_test)

linear_mae = mean_absolute_error(y_test, linear_predictions)
linear_rmse = np.sqrt(mean_squared_error(y_test, linear_predictions))
linear_r2 = r2_score(y_test, linear_predictions)

print("Linear Regression Results")
print("MAE:", linear_mae)
print("RMSE:", linear_rmse)
print("R2 Score:", linear_r2)

"""##Random Forest model"""

# 12. Random Forest Regressor

rf_model = RandomForestRegressor(random_state=42)
rf_model.fit(X_train, y_train)

rf_predictions = rf_model.predict(X_test)

rf_mae = mean_absolute_error(y_test, rf_predictions)
rf_rmse = np.sqrt(mean_squared_error(y_test, rf_predictions))
rf_r2 = r2_score(y_test, rf_predictions)

print("Random Forest Results")
print("MAE:", rf_mae)
print("RMSE:", rf_rmse)
print("R2 Score:", rf_r2)

"""##Feature importance"""

# 13. Feature importance from Random Forest

feature_importance = pd.DataFrame({
    "feature": X.columns,
    "importance": rf_model.feature_importances_
}).sort_values(by="importance", ascending=False)

feature_importance.head(10)

# Plot top 10 important features

plt.figure(figsize=(10, 6))
sns.barplot(
    data=feature_importance.head(10),
    x="importance",
    y="feature"
)
plt.title("Top 10 Important Features for Life Expectancy Prediction")
plt.xlabel("Importance")
plt.ylabel("Feature")
plt.show()

"""##Model comparison"""

# 14. Model comparison

model_results = pd.DataFrame({
    "Model": ["Linear Regression", "Random Forest"],
    "MAE": [linear_mae, rf_mae],
    "RMSE": [linear_rmse, rf_rmse],
    "R2 Score": [linear_r2, rf_r2]
})

model_results

"""## Key insights template

At the end of the notebook, add this as markdown:

## Key Insights

- Life expectancy shows variation across countries and years.
- Health-related indicators such as adult mortality and disease burden are expected to strongly influence life expectancy.
- Socio-economic indicators such as schooling and income composition may also be related to life expectancy.
- The Random Forest model may capture non-linear relationships better than a simple Linear Regression model.
- Further analysis can improve feature selection, model tuning, and interpretation.

## Conclusion

This project demonstrates how data analysis and machine learning can be used to explore public health indicators related to life expectancy. The project can be improved by adding more visualizations, model comparison, explainability methods, and a Streamlit dashboard.
"""

